### ISSUE TITLE
Handshake with APP

### ISSUE THREAD

**Issue by KocurMaros** [timmmmimmm/VRS_Mouse_App#1]
1. Create  verifier with timer
- [x] device - sending string to USART (Serial Number/MAC address)
- [ ] APP - waiting for string on USART (when it comes stop sending device verifier)
- [ ] after established connection read param from EEPROM/FLASH and send them to APP
- [ ]  wait for param from APP 
- [ ] write param to EEPROM/flash

**Comment by timmmmimmm** [comment]
Bruuh, that was did like half a year ago
